export const projects = [
  {
    id: 'hamah-tools',
    title: 'Hamah Tools',
    description:
      'Internal agency hub — AI proposal creator, admin panel, EN/AR RTL.',
    tags: ['React 19', 'TypeScript', 'Vite'],
    image: '/MAS_5458-nbg1.png',
    href: 'https://hamah-tools.hi-lab.ai',
    external: true,
  },
  {
    id: 'healthcare',
    title: 'Healthcare Assessment',
    description: 'Multi-tenant healthcare platform with React + Node API.',
    tags: ['React', 'Node.js', 'MySQL'],
    image: '/MAS_5458-nbg1.png',
    href: 'https://app.thrivenine.life',
    external: true,
  },
  {
    id: 'flowtack',
    title: 'Flowtack Web Builder',
    description: 'Visual web builder with GrapesJS and React.',
    tags: ['React', 'GrapesJS', 'MUI'],
    image: '/MAS_5458-nbg1.png',
    href: 'https://www.app.flowtrack.co',
    external: true,
  },
  {
    id: 'lorawan',
    title: 'DoS in LoRaWAN',
    description: 'MS Cyber Security thesis — NS-3 simulation & mitigation.',
    tags: ['C++', 'NS-3', 'LoRaWAN'],
    image: '/MAS_5458-nbg1.png',
    href: 'https://github.com/alihafeez337/lorawan',
    external: true,
  },
  {
    id: 'fleet',
    title: 'Fleet Management D3',
    description: 'Real-time fleet boards with Vue, D3, and Socket.IO.',
    tags: ['Vue', 'D3.js', 'Node'],
    image: '/MAS_5458-nbg1.png',
    href: 'https://board-ac1a6.web.app',
    external: true,
  },
  {
    id: 'i2c-assessment',
    title: 'i2c Assessment UI',
    description: 'Figma-to-code marketing sample in this repo.',
    tags: ['Next.js', 'React', 'CSS'],
    image: '/MAS_5458-nbg1.png',
    href: '/portfolio/i2c-assessment',
    external: false,
  },
];
